/*
generated by comer,https://github.com/imoowi/comer
Copyright © 2023 jun<simpleyuan@gmail.com>
*/
package services

import (
	"codee_jun/internal/components"
	"codee_jun/internal/interfaces"
	"codee_jun/internal/models"
	"codee_jun/internal/repos"
	"fmt"
	"runtime"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/nats-io/nats.go"
	"github.com/spf13/cast"
	"go.uber.org/zap"
)

var Order *OrderService

// OrderService 订单服务
// 封装了订单的增删改查功能，并集成了NATS消息队列进行异步处理
type OrderService struct {
	interfaces.Service[*models.Order]                        // 基础服务接口，提供CRUD操作
	nb                                *components.NatsBroker // NATS消息队列代理，用于发布订阅消息
}

// NewOrderService 创建订单服务实例
// 初始化NATS连接，并注入订单仓储层
// 返回初始化完成的OrderService实例
func NewOrderService(r *repos.OrderRepo) *OrderService {
	nb, err := components.NewNatsBroker()
	if err != nil {
		panic(err)
	}
	// defer nb.NC.Close()
	_odS := &OrderService{
		Service: *interfaces.NewService(repos.Order),
		nb:      nb,
	}
	go _odS.JsWorker()
	return _odS
}

func init() {
	RegisterServices(func() {
		Order = NewOrderService(repos.Order)
	})
}

// Add 添加订单
// 在数据库中创建订单记录，成功后异步发布订单创建事件到NATS
// 参数 c: gin上下文，order: 订单数据
// 返回新订单ID和可能的错误
func (s *OrderService) Add(c *gin.Context, order *models.Order) (newId uint, err error) {
	id, err := s.Service.Add(c, order)
	if err == nil && id > 0 {
		go s.PublishJs(order)
	}
	return id, nil
}

// PublishJs 发布订单创建事件到NATS JetStream
// 将订单ID发布到"orders.created"主题，供其他服务订阅处理
// 参数 order: 订单数据
func (s *OrderService) PublishJs(order *models.Order) {
	_subject := "orders.created"
	_data := []byte(cast.ToString(order.ID))
	s.nb.JS.Publish(_subject, _data)
}

// JsWorker 订单事件消费者
// 订阅"orders.created"主题，处理订单创建事件
// 实现了消息确认和重试机制：
// - 消息处理成功时调用Ack确认
// - 消息处理失败时，根据重试次数决定是否延迟重试或终止消息
// - 最多重试5次，重试延迟采用指数退避策略（n²秒）
// 该方法会阻塞当前goroutine，需要在独立的goroutine中运行
func (s *OrderService) JsWorker() {
	_subject := "orders.created"
	_, err := s.nb.JS.QueueSubscribe(_subject, "order_worker", func(msg *nats.Msg) {
		orderId := string(msg.Data)
		zap.L().Info("order.worker", zap.String("orderId", orderId))

		err := s.processOrderCreatedEvent()
		if err != nil {
			zap.L().Error("order.worker", zap.Error(err))
			meta, _ := msg.Metadata()
			numdDelivered := meta.NumDelivered
			if numdDelivered < 3 {
				delay := time.Duration(numdDelivered*numdDelivered) * time.Second
				msg.NakWithDelay(delay)
			} else {
				msg.Term()
			}
			return
		}
		msg.Ack()

	}, nats.ManualAck(), nats.MaxDeliver(5))
	if err != nil {
		panic(err)
	}
	runtime.Goexit()
}

// processOrderCreatedEvent 处理订单创建事件
// 模拟订单事件处理逻辑，偶数时间戳会返回错误用于测试重试机制
// 返回处理过程中的错误
func (s *OrderService) processOrderCreatedEvent() error {
	if time.Now().Unix()%2 == 0 {
		return fmt.Errorf("order created event is even")
	}
	return nil
}
