/*
generated by comer,https://github.com/imoowi/comer
Copyright © 2023 jun<simpleyuan@gmail.com>
*/
package routers

import (
	"codee_jun/internal/controllers"

	"github.com/gin-gonic/gin"
)

func init() {
	RegisterRoute(OrderRouters)
}

func OrderRouters(e *gin.Engine) {
	api := e.Group("/api")
	// api.Use(middlewares.AuthMiddleware())
	orders := api.Group("/orders")
	{
		orders.GET("", controllers.OrderPageList)   //分页
		orders.GET("/:id", controllers.OrderOne)    //一个
		orders.POST("", controllers.OrderAdd)       //新增
		orders.PUT("/:id", controllers.OrderUpdate) //更新
		orders.DELETE("/:id", controllers.OrderDel) //软删除
	}
}
