/*
generated by comer,https://github.com/imoowi/comer
Copyright © 2023 jun<simpleyuan@gmail.com>
*/
package migrates

import (
	"codee_jun/internal/models"

	"gorm.io/gorm"
)

func init() {
	regMigrate(func(d *gorm.DB) {
		d.AutoMigrate(&models.Order{})
	})
}
