/*
generated by comer,https://github.com/imoowi/comer
Copyright © 2023 jun<simpleyuan@gmail.com>
*/
package repos

import (
	"codee_jun/internal/components"
	"codee_jun/internal/interfaces"
	"codee_jun/internal/models"
)

var Order *OrderRepo

type OrderRepo struct {
	interfaces.Repo[*models.Order]
}

func NewOrderRepo() {
	Order = &OrderRepo{
		Repo: *interfaces.NewRepo[*models.Order](components.DB),
	}
}

func init() {
	RegisterRepos(NewOrderRepo)
}
