/*
generated by comer,https://github.com/imoowi/comer
Copyright © 2023 jun<simpleyuan@gmail.com>
*/
package router

import (
	"user-service/internal/controllers"
	"user-service/internal/middlewares"

	"github.com/gin-gonic/gin"
)

func init() {
	RegisterRoute(AuthRouters)
}

func AuthRouters(e *gin.Engine) {
	api := e.Group(`/api/user`)
	{
		api.POST(`/auth-login`, middlewares.VcodeMiddleware(), controllers.AuthLogin)
		api.GET(`/auth-logout`, middlewares.ApisixMiddleware(), controllers.AuthLogout)
		api.GET(`/auth-info`, middlewares.ApisixMiddleware(), controllers.AuthInfo)
	}
}
