/*
generated by comer,https://github.com/imoowi/comer
Copyright © 2023 jun<simpleyuan@gmail.com>
*/
package router

import (
	"user-service/internal/controllers"

	"github.com/gin-gonic/gin"
)

func init() {
	RegisterRoute(CommonRouters)
}

func CommonRouters(e *gin.Engine) {
	auth := e.Group(`/api/user/common`)
	{
		auth.GET(`/captcha`, controllers.Captcha)
	}
}
