/*
generated by comer,https://github.com/imoowi/comer
Copyright © 2023 jun<simpleyuan@gmail.com>
*/
package router

import (
	"user-service/internal/middlewares"

	"github.com/gin-gonic/gin"
	"github.com/imoowi/comer/utils/response"
)

type Router func(*gin.Engine)

var routers = []Router{}

func InitRouter() *gin.Engine {
	r := gin.Default()
	middlewares.InitMiddleware(r)
	for _, route := range routers {
		route(r)

	}
	r.GET(`/api/user/casbins/allapi`, func(ctx *gin.Context) {

		// @Router       /api/user/casbins/allapi [get]
		routers := r.Routes()
		allapi := make([]map[string]string, 0)
		for _, v := range routers {
			allapi = append(allapi, map[string]string{"method": v.Method, "path": v.Path})
		}
		response.OK(ctx, allapi)
	})
	return r
}

func RegisterRoute(r ...Router) {
	routers = append(routers, r...)
}
