/*
generated by comer,https://github.com/imoowi/comer
Copyright © 2023 jun<simpleyuan@gmail.com>
*/
package middlewares

import (
	"net/http"
	"user-service/internal/services"

	"github.com/gin-gonic/gin"
	"github.com/imoowi/comer/utils/response"
	"github.com/spf13/cast"
)

func ApisixMiddleware() func(c *gin.Context) {
	return func(c *gin.Context) {
		authHeader := c.Request.Header.Get("Authorization")
		if authHeader == "" {
			response.Error(c, "请求头中auth为空", http.StatusUnauthorized)
			return
		}
		//判断用户是否主动注销过
		isLogouted := services.User.IsLogouted(c, authHeader)
		if isLogouted {
			response.Error(c, "token 失效", http.StatusUnauthorized)
			return
		}
		//检测apisix过来的用户id有没有
		userId := c.GetHeader("X-User-Id")
		if userId == "" {
			response.Error(c, "X-User-Id  is empty", http.StatusUnauthorized)
			return
		}

		//绝对信任上游传递的用户id
		c.Set("uid", cast.ToUint(userId))
		c.Next()
	}
}
