apiVersion: apps/v1 #定义应用部署的API版本
kind: Deployment #定义部署应用
metadata: #元数据部分
  name: golang-per-day #这里填写部署名称
  namespace: codee_jun #这里填写命名空间
spec:
  #replicas表示期望运行的Pod副本数量
  replicas: 1 #这里填写副本数量
  #选择器，定义如何选择Pod
  selector:
    matchLabels: #选择标签，匹配具有特定标签的Pod
      app: golang-per-day #这里填写标签名称
  #模板，定义Pod的规格
  template:
    metadata: #Pod的元数据
      labels: #标签部分
        app: golang-per-day #这里填写标签名称
    spec: #Pod的规格部分
      containers: #定义容器
        - name: golang-per-day #这里填写容器名称
          image: golang_per_day_24:latest #这里填写镜像名称
          ports: #定义容器端口
            - containerPort: 80 #容器内部端口
          volumeMounts: #定义卷挂载
            - name: runtime-dir
              mountPath: /configs #容器内挂载路径
              subPath: runtime/golang_per_day_24/configs #子路径
          resources: #定义资源请求和限制
            requests: #资源请求
              cpu: 35m #请求的CPU资源
              memory: 380Mi #请求的内存资源
            limits: #资源限制
              cpu: 70m #限制的CPU资源
              memory: 500Mi #限制的内存资源
      volumes:
        - name: runtime-dir #卷名称
          persistentVolumeClaim: 
            claimName: nfs-pvc #引用的持久卷声明名称
---
apiVersion: v1
kind: Service #定义服务
metadata:
  name: golang-per-day #这里填写服务名称
  namespace: codee_jun #这里填写命名空间
spec: #服务规格
  # externalIPs:
  #   - 123.59.187.137
  ports:
    - protocol: TCP 
      port: 80 #服务端口
      targetPort: 80 #目标端口（容器端口）
  sessionAffinity: ClientIP #会话亲和性设置为ClientIP
  selector: 
    app: golang-per-day  #选择标签，匹配具有特定标签的Pod
---
apiVersion: autoscaling/v2 
kind: HorizontalPodAutoscaler #定义水平Pod自动扩缩容器
metadata:
  name: golang-per-day-hpa #这里填写HPA名称
  namespace: codee_jun #这里填写命名空间
spec: 
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment 
    name: golang-per-day
  minReplicas: 1 #最小副本数
  maxReplicas: 10 #最大副本数
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization #CPU利用率目标
          averageUtilization: 90 #CPU利用率目标值
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization #内存利用率目标
          averageUtilization: 90 #内存利用率目标值